
#system define
spring.application.name=platform-SpringBoot
server.port=8088
# database config
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:src/main/resources/sqlitedb/database.db
#spring.datasource.url=jdbc:sqlite:src/main/resources/sqlitedb/platform.db
spring.datasource.username=
spring.datasource.password=
#log level
#logging.level.root = debug
#logging.level.com.hyw.platform = debug
#logging.level.com.hyw.platform.mapper = debug