
#system define
spring.application.name=platform-SpringBoot
server.port=8088
# database config
spring.datasource.driver-class-name=org.sqlite.JDBC
#
spring.datasource.url=jdbc:sqlite:D:/ideaSpace/hywSource/platform/src/main/resources/sqlitedb/database.db
#spring.datasource.url=jdbc:sqlite:E:/javasource/Platform/src/main/resources/sqlitedb/database.db
spring.datasource.username=
spring.datasource.password=

# ?????? Trace ID
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n


#log level
#logging.level.root = debug
#logging.level.com.hyw.platform = debug
#logging.level.com.hyw.platform.mapper = debug

#?????????
service.host.env=sit3